# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: michelleblog_development

test:
  <<: *default
  database: michelleblog_test

production:
  <<: *default
  database: michelleblog_production
  username: michelleblog
  password: <%= ENV['MICHELLEBLOG_DATABASE_PASSWORD'] %>
